export const state = {
  menu: [
    {
      name: 'birthday',
      description: 'HOA SINH NHẬT',
      submenu: [
        'HOA SINH NHẬT SANG TRỌNG',
        'HOA SINH NHẬT GIÁ RẺ',
        'HOA TẶNG SINH NHẬT NGƯỜI YÊU',
        'HOA TẶNG SINH NHẬT MẸ',
        'HOA TẶNG SINH NHẬT BẠN',
        'LẴNG HOA TẶNG SINH NHẬT',
        'HOA HÒNG TẶNG SINH NHẬT',
        'GIỎ HOA SINH NHẬT',
      ],
    },
    {
      name: 'opening',
      description: 'HOA KHAI TRƯƠNG',
      submenu: [
        'HOA KHAI TRƯƠNG ĐỂ BÀN',
        'KỆ HOA KHAI TRƯƠNG',
        'HOA KHAI TRƯƠNG GIÁ RẺ',
        'LẴNG HOA 2 TẦNG MỪNG KHAI TRƯƠNG',
      ],
    },
    {
      name: 'topic',
      description: 'CHỦ ĐỀ',
      submenu: [
        'HOA CHÚC MỪNG',
        'HOA CƯỚI CÀM TAY',
        'HOA TANG LỄ - HOA CHIA BUỒN',
        'HOA TÌNH YÊU',
        'HOA VALENTINE',
        'HOA KỶ NIỆM NGÀY CƯỚI',
        'NGÀY CỦA MẸ',
        'NGÀY 8-3',
        'NGÀY 20-10',
        'NGÀY NHÀ GIÁO VN',
        'GIÁNG SINH',
        'TẾT ÂM LỊCH',
        'HOA TÓT NGHIỆP',
        'HOA ĐỊNH KỲ',
      ],
    },
    {
      name: 'design',
      description: 'THIẾT KẾ',
      submenu: [
        'BÓ HOA',
        'LẴNG HOA',
        'GIỎ HOA',
        'KỆ HOA',
        'BÌNH HOA',
        'HỘP HOA',
      ],
    },
    {
      name: 'fresh',
      description: 'HOA TƯƠI',
      submenu: [
        'HOA HỒNG',
        'HOA LY',
        'HOA LAN HỒ ĐIỆP',
        'HOA SEN',
        'HOA ĐỒNG TIÈN',
        'HOA CẨM CHƯỚNG',
        'HOA HƯỚNG DƯƠNG',
        'HOA TULIP',
        'HOA MẪU ĐƠN',
        'HOA CẨM TÚ CẦU',
        'HOA BABY',
        'HOA THẠCH THẢO',
        'HOA CÚC HỌA MI',
      ],
    },
    {
      name: 'gift',
      description: 'QUÀ TẶNG',
      submenu: [
        'GẤU BÔNG',
        'SOCOLA',
        'BÁNH KEM',
        'GIỎ TRÁI CÂY',
        'GIỎ QUÀ TẶNG',
        'HOA GIẢ',
      ],
    },

    {
      name: 'from199k',
      description: 'HOA TỪ 199K',
      submenu: [],
    },
  ],
};
