export const state = {
  menu: [
    {
      name: 'birthday',
      description: 'HOA SINH NHẬT',
      submenu: [
        'HOA SINH NHẬT SANG TRỌNG',
        'HOA SINH NHẬT GIÁ RẺ',
        'HOA TẶNG SINH NHẬT NGƯỜI YÊU',
        'HOA TẶNG SINH NHẬT MẸ',
        'HOA TẶNG SINH NHẬT BẠN',
        'LẴNG HOA TẶNG SINH NHẬT',
        'HOA HÒNG TẶNG SINH NHẬT',
        'GIỎ HOA SINH NHẬT',
      ],
    },
    {
      name: 'opening',
      description: 'HOA KHAI TRƯƠNG',
      submenu: [
        'HOA KHAI TRƯƠNG ĐỂ BÀN',
        'KỆ HOA KHAI TRƯƠNG',
        'HOA KHAI TRƯƠNG GIÁ RẺ',
        'LẴNG HOA 2 TẦNG MỪNG KHAI TRƯƠNG',
      ],
    },
    {
      name: 'topic',
      description: 'CHỦ ĐỀ',
      submenu: [
        'HOA CHÚC MỪNG',
        'HOA CƯỚI CÀM TAY',
        'HOA TANG LỄ - HOA CHIA BUỒN',
        'HOA TÌNH YÊU',
        'HOA VALENTINE',
        'HOA KỶ NIỆM NGÀY CƯỚI',
        'NGÀY CỦA MẸ',
        'NGÀY 8-3',
        'NGÀY 20-10',
        'NGÀY NHÀ GIÁO VN',
        'GIÁNG SINH',
        'TẾT ÂM LỊCH',
        'HOA TÓT NGHIỆP',
        'HOA ĐỊNH KỲ',
      ],
    },
    {
      name: 'design',
      description: 'THIẾT KẾ',
      submenu: [
        'BÓ HOA',
        'LẴNG HOA',
        'GIỎ HOA',
        'KỆ HOA',
        'BÌNH HOA',
        'HỘP HOA',
      ],
    },
    {
      name: 'fresh',
      description: 'HOA TƯƠI',
      submenu: [
        'HOA HỒNG',
        'HOA LY',
        'HOA LAN HỒ ĐIỆP',
        'HOA SEN',
        'HOA ĐỒNG TIÈN',
        'HOA CẨM CHƯỚNG',
        'HOA HƯỚNG DƯƠNG',
        'HOA TULIP',
        'HOA MẪU ĐƠN',
        'HOA CẨM TÚ CẦU',
        'HOA BABY',
        'HOA THẠCH THẢO',
        'HOA CÚC HỌA MI',
      ],
    },
    {
      name: 'gift',
      description: 'QUÀ TẶNG',
      submenu: [
        'GẤU BÔNG',
        'SOCOLA',
        'BÁNH KEM',
        'GIỎ TRÁI CÂY',
        'GIỎ QUÀ TẶNG',
        'HOA GIẢ',
      ],
    },

    {
      name: 'from199k',
      description: 'HOA TỪ 199K',
      submenu: [],
    },
  ],
  topics: [
    {
      img: './img/topics/hoa-tinh-yeu.webp',
      name: 'HOA TÌNH YÊU',
    },
    {
      img: './img/topics/hoa-sinh-nhat.webp',
      name: 'HOA SINH NHẬT',
    },
    {
      img: './img/topics/hoa-cuoi.webp',
      name: 'HOA CƯỚI',
    },
    {
      img: './img/topics/hoa-lan.webp',
      name: 'HOA LAN',
    },
    {
      img: './img/topics/hoa-khai-truong.webp',
      name: 'HOA KHAI TRƯƠNG',
    },
    {
      img: './img/topics/hoa-chia-buon.webp',
      name: 'HOA CHIA BUỒN',
    },
  ],
  feartures: [
    {
      header: 'Free Shipping',
      img: './img/feartures/fearture1.png',
      description:
        'Flower Corner giao miễn phí các Quận 1,3,4,5,6,7,8,10,11,Tân Bình,Tân Phú,Phú Nhuận,Bình Thạnh đối với tất cả bó hoa, lẵng hoa, và kệ hoa trên 1 triệu.',
    },
    {
      header: 'Giao nhanh trong 90 phút',
      img: './img/feartures/fearture2.png',
      description:
        "Flower Corner có thể giao nhanh trong 90' khu vực nội thành TP.HCM với bó hoa hoặc lẵng hoa đơn giản.",
    },
    {
      header: 'Hoa đẹp như hình',
      img: './img/feartures/fearture3.png',
      description:
        'Cam kết hoa đẹp như hình và giống đến 90% so với hình chụp trên website.',
    },
  ],
  products: [
    {
      className: '.sales',
      title: 'Đang Giảm Giá',
      items: [
        {
          img: './img/products/sales/sales1.jpg',
          name: 'Bó Hoa Sắc Màu',
          isSale: true,
          saleRate: '16%',
          price: 200000,
          salePrice: 170000,
          rate: 0,
        },
        {
          img: './img/products/sales/sales2.jpg',
          name: 'Màu Nắng Ấm',
          isSale: true,
          saleRate: '13%',
          price: 330000,
          salePrice: 290000,
          rate: 0,
        },
        {
          img: './img/products/sales/sales3.jpg',
          name: 'Trái Tim Nhỏ',
          isSale: true,
          saleRate: '21%',
          price: 490000,
          salePrice: 390000,
          rate: 0,
        },
        {
          img: './img/products/sales/sales4.jpg',
          name: 'Giỏ Hoa Thạch Thảo Yêu Kiều',
          isSale: true,
          saleRate: '17%',
          price: 590000,
          salePrice: 490000,
          rate: 5,
        },
      ],
    },
    {
      className: '.fast-shipping',
      title: "Giao Nhanh 90'",
      items: [
        {
          img: './img/products/fast-shipping/fast-shipping1.jpg',
          name: 'Giọt Nắng',
          isSale: true,
          saleRate: '20%',
          price: 210000,
          salePrice: 170000,
          rate: 0,
        },
        {
          img: './img/products/fast-shipping/fast-shipping2.jpg',
          name: 'Một Tình Yêu',
          isSale: false,
          saleRate: '',
          price: 220000,
          salePrice: 0,
          rate: 0,
        },
        {
          img: './img/products/fast-shipping/fast-shipping3.jpg',
          name: 'Bó Hoa Nắng Mới',
          isSale: true,
          saleRate: '19%',
          price: 430000,
          salePrice: 350000,
          rate: 5,
        },
        {
          img: './img/products/fast-shipping/fast-shipping4.jpg',
          name: 'Hộp Tình Yêu',
          isSale: false,
          saleRate: '',
          price: 390000,
          salePrice: 0,
          rate: 0,
        },
      ],
    },
    {
      className: '.new',
      title: 'Sản Phẩm Mới',
      items: [
        {
          img: './img/products/new/new1.jpg',
          name: 'My Juliet',
          isSale: false,
          saleRate: '',
          price: 210000,
          salePrice: 0,
          rate: 0,
        },
        {
          img: './img/products/new/new2.jpg',
          name: 'Spring Time',
          isSale: true,
          saleRate: '16%',
          price: 450000,
          salePrice: 380000,
          rate: 0,
        },
        {
          img: './img/products/new/new3.jpg',
          name: 'Evermore',
          isSale: true,
          saleRate: '7%',
          price: 480000,
          salePrice: 450000,
          rate: 0,
        },
        {
          img: './img/products/new/new4.jpg',
          name: 'Vườn Hồng',
          isSale: true,
          saleRate: '10%',
          price: 750000,
          salePrice: 680000,
          rate: 0,
        },
      ],
    },
    {
      className: '.birthday',
      title: 'Hoa Sinh Nhật',
      items: [
        {
          img: './img/products/birthday/birthday1.jpg',
          name: 'Pink Moon',
          isSale: false,
          saleRate: '',
          price: 380000,
          salePrice: 0,
          rate: 0,
        },
        {
          img: './img/products/birthday/birthday2.jpg',
          name: 'Perfect',
          isSale: true,
          saleRate: '28%',
          price: 790000,
          salePrice: 570000,
          rate: 5,
        },
        {
          img: './img/products/birthday/birthday3.jpg',
          name: 'Mây Mộng Mơ',
          isSale: false,
          saleRate: '',
          price: 500000,
          salePrice: 0,
          rate: 5,
        },
        {
          img: './img/products/birthday/birthday4.jpg',
          name: 'Pure Love',
          isSale: false,
          saleRate: '',
          price: 520000,
          salePrice: 0,
          rate: 5,
        },
      ],
    },
    {
      className: '.opening',
      title: 'Hoa Khai Trương',
      items: [
        {
          img: './img/products/opening/opening1.jpg',
          name: 'Kệ Hoa Khai Trương Nhiệt Huyết',
          isSale: false,
          saleRate: '',
          price: 640000,
          salePrice: 0,
          rate: 0,
        },
        {
          img: './img/products/opening/opening2.jpg',
          name: 'Hoa Khai Trương Cát Tường',
          isSale: true,
          saleRate: '3%',
          price: 800000,
          salePrice: 780000,
          rate: 0,
        },
        {
          img: './img/products/opening/opening3.jpg',
          name: 'Kệ Hoa Chúc Mừng Hồng Phát 2',
          isSale: true,
          saleRate: '7%',
          price: 1090000,
          salePrice: 1020000,
          rate: 0,
        },
        {
          img: './img/products/opening/opening4.jpg',
          name: 'Kệ Hoa Khai Trương Thịnh Phát',
          isSale: false,
          saleRate: '',
          price: 1310000,
          salePrice: 0,
          rate: 0,
        },
      ],
    },
    {
      className: '.sad',
      title: 'Hoa Chia Buồn',
      items: [
        {
          img: './img/products/sad/sad1.jpg',
          name: 'Hoa Chia Buồn Thành Kính',
          isSale: false,
          saleRate: '',
          price: 750000,
          salePrice: 0,
          rate: 0,
        },
        {
          img: './img/products/sad/sad2.jpg',
          name: 'Vòng Hoa Tan Lễ Nhớ Thương',
          isSale: false,
          saleRate: '',
          price: 820000,
          salePrice: 0,
          rate: 0,
        },
        {
          img: './img/products/sad/sad3.jpg',
          name: 'Hoa Chia Buồn Tiễn Biệt',
          isSale: false,
          saleRate: '',
          price: 820000,
          salePrice: 0,
          rate: 5,
        },
        {
          img: './img/products/sad/sad4.jpg',
          name: 'Hoa Chia Buồn Đồng Cảm',
          isSale: false,
          saleRate: '',
          price: 950000,
          salePrice: 0,
          rate: 0,
        },
      ],
    },
    {
      className: '.fruits',
      title: 'Giỏ Trái Cây',
      items: [
        {
          img: './img/products/fruits/fruits1.jpg',
          name: 'Giỏ Trái Cây Thơm Ngon',
          isSale: false,
          saleRate: '',
          price: 1720000,
          salePrice: 0,
          rate: 0,
        },
        {
          img: './img/products/fruits/fruits2.jpg',
          name: 'Mát Lành',
          isSale: false,
          saleRate: '',
          price: 1980000,
          salePrice: 0,
          rate: 0,
        },
        {
          img: './img/products/fruits/fruits3.jpg',
          name: 'Niềm Hạnh Phúc',
          isSale: false,
          saleRate: '',
          price: 2060000,
          salePrice: 0,
          rate: 0,
        },
        {
          img: './img/products/fruits/fruits4.jpg',
          name: 'Sang Trọng',
          isSale: false,
          saleRate: '',
          price: 2080000,
          salePrice: 0,
          rate: 0,
        },
      ],
    },
  ],
};
